### ISSUE TITLE
How to decompile and get Animation on blender to play it 

### ISSUE THREAD

**Issue by gamersalpha** [CrishNate/Gmod-Replicators#4]
Hello how to decompile and get animation on blander to play with this 

thanks all

**Comment by CrishNate** [comment]
Hello. I can just provide you with a blender rig, if you need a model.

You need both replicator and queen, right?

**Comment by gamersalpha** [comment]
Hello Yes 👍
Thanks

**Comment by CrishNate** [comment]
https://drive.google.com/file/d/1VSus6tQQ23CdqCCjauLJNVd33AJLtU-_/view?usp=sharing

**Comment by gamersalpha** [comment]
Hello 

Really thanks 


I import the model and animation on my godot engine 

Just missing an attack animation


Now I have to finish to code 

Thanks 👍👍👍👍

**Comment by CrishNate** [comment]
Hello,

No problem, use them as you wish :)
